#!/usr/bin/python3

"""
Combines nearby interactions generated by FitHiChIP
by a connected component labeling algorithm

Author: Sourya Bhattacharyya
Vijay-Ay lab, LJI
"""

import os
import sys
import math
from optparse import OptionParser
import networkx as nx
import queue
import heapq

#==========================================================
def custom_percent(lst, K, order=1):
    if (order == 1):
        sortedLst = sorted(lst)
    else:
        sortedLst = sorted(lst, reverse=True)
    lstLen = len(lst)
    index = int(((len(lst) * K) / 100))
    if (index <= 1):
        if (order == 1):
            return max(sortedLst)
        else:
            return min(sortedLst)
    return sortedLst[index]

class Interaction(object):  
    def __init__(self, cc, pval, qval):
        self.contact = cc
        self.PValue = pval
        self.QValue = qval

    def _GetCC(self):
        return self.contact

    def _GetPVal(self):
        return self.PValue

    def _GetQVal(self, count=1):
        return self.QValue

#===============================================
def main():
    parser = OptionParser()
    parser.add_option("--InpFile", dest="InpFile", help="Input interaction file. Assumed that the first six fields contain two interacting chromosome information.")
    parser.add_option("--headerInp", dest="headerInp", type="int", help="If 1, indicates that input interaction file has a header line (such as field names). Default 1.")
    parser.add_option("--OutFile", dest="OutFile", help="Output merged interaction file")
    parser.add_option("--binsize", dest="binsize", type="int", help="Size of bins employed. DEFAULT 5 Kb.")
    parser.add_option("--conn", dest="connectivity_rule", type="int", help="Rule of connectivity ( 8 or 4). DEFAULT 8.")
    parser.add_option("--percent", dest="TopPctElem", type="int", help="Percentage of elements to be selected from each connected component. Default: 100.")
    parser.add_option("--Neigh", dest="NeighborHoodBin", type="int", help="Positive integer (default: 2 with 5 Kb bin size) means that if a loop is included in the final set, loops involving within 2x2 neighborhood of both the bins would be discarded.")
    parser.add_option("--cccol", dest="CCCol", type="int", help="Column number storing the contact count. Default: 7.")    
    parser.add_option("--qcol", dest="QValCol", type="int", help="Column number storing the q-value. Default: 0, means the last column.")
    parser.add_option("--pcol", dest="PValCol", type="int", help="Column number storing the p-value. Default: 0, means the second last column.")
    parser.add_option("--order", dest="SortOrder", type="int", help="Binary variable indicating the sorting order of significance values. Default 0, means ascending order.")
    parser.set_defaults(InpFile=None, OutFile=None, binsize=5000, connectivity_rule=8, headerInp=1, TopPctElem=100, NeighborHoodBin=2, QValCol=0, PValCol=0, SortOrder=0, CCCol=7)
    (options, args) = parser.parse_args()

    # process the input parameters
    if options.InpFile is not None:
        InpFile = options.InpFile
    else:
        sys.exit("Input file is not provided - quit !!")
    if options.OutFile is not None:
        OutFile = options.OutFile
    else:
        sys.exit("Output file is not specified - quit !!")

    bin_size = int(options.binsize)
    headerInp = int(options.headerInp)
    connectivity_rule = int(options.connectivity_rule)
    TopPctElem = int(options.TopPctElem)
    NeighborHoodBinThr = (int(options.NeighborHoodBin)) * bin_size
    QValCol = int(options.QValCol)
    PValCol = int(options.PValCol)
    CCCol = int(options.CCCol)
    SortOrder = int(options.SortOrder)

    # fix the columns containing P and Q-values
    fp_in = open(InpFile, 'r')
    l = fp_in.readline()
    contents = l.rstrip().split()
    if (QValCol == 0):
        QValCol = len(contents)
    if (PValCol == 0):
        PValCol = (len(contents) - 1)
    fp_in.close()

    # print the parameters
    print('****** Merge filtering of adjacent loops is enabled *****')
    print('***** within function of merged filtering - printing the parameters ***')
    print('*** bin_size: ', bin_size)
    print('*** headerInp: ', headerInp)
    print('*** connectivity_rule: ', connectivity_rule)
    print('*** TopPctElem: ', TopPctElem)
    print('*** NeighborHoodBinThr: ', NeighborHoodBinThr)
    print('*** QValCol: ', QValCol)
    print('*** PValCol: ', PValCol)
    print('*** SortOrder: ', SortOrder)

    # output directory
    OutDir = os.path.dirname(os.path.realpath(OutFile))
    print('OutDir: ', str(OutDir))
    os.makedirs(OutDir, exist_ok=True)  # Ensure output directory exists

    # open the output file
    fp_outInt = open(OutFile, 'w')

    # write header
    if (headerInp == 1):
        fp_in = open(InpFile, 'r')
        l = fp_in.readline()
        contents = l.rstrip().split()
        fp_outInt.write(contents[0] + '\t' + contents[1] + '\t' + contents[2] + '\t' + contents[3] + '\t' + contents[4] + '\t' + contents[5] + '\t' + contents[CCCol-1] + '\t' + contents[PValCol - 1] + '\t' + contents[QValCol - 1] + '\t' + 'bin1_low' + '\t' + 'bin1_high' + '\t' + 'bin2_low' + '\t' + 'bin2_high' + '\t' + 'sumCC' + '\t' + 'StrongConn\n')
        fp_in.close()
    else:
        fp_outInt.write('chr1\tstart1\tend1\tchr2\tstart2\tend2\tCC\tp\tfdr\tbin1_low\tbin1_high\tbin2_low\tbin2_high\tsumCC\tStrongConn\n')

    # get the chromosome list
    TargetChrList = []
    temp_chr_log_file = OutDir + '/Temp_chromosome_list.log'
    sys_cmd = "awk -F\'[\t]\' \'{if (NR > 1) {print $1}}\' " + str(InpFile) + " | sort -k1,1 | uniq > " + str(temp_chr_log_file)
    os.system(sys_cmd)
    with open(temp_chr_log_file, 'r') as fp_in:
        for l in fp_in.readlines():
            currchrname = (l.rstrip()).split()[0]
            TargetChrList.append(currchrname)
    print('list of chromosomes: ', str(TargetChrList))
    os.system("rm " + temp_chr_log_file)

    # Initialize tempchrdumpfile
    tempchrdumpfile = OutDir + '/Temp_chr_Dump.bed'

    # loop to process individual chromosomes
    for chridx in range(len(TargetChrList)):
        curr_chr = TargetChrList[chridx]
        print('Processing the chromosome: ', str(curr_chr))

        # extract interactions
        awkcmd = "cat " + str(InpFile) + " | awk \'{if (NR>1 && $1==\"" + str(curr_chr) + "\" && $4==\"" + str(curr_chr) + "\"){print $0}}\' -  > " + str(tempchrdumpfile)
        if headerInp == 0:
            awkcmd = "cat " + str(InpFile) + " | awk \'{if ($1==\"" + str(curr_chr) + "\" && $4==\"" + str(curr_chr) + "\"){print $0}}\' -  > " + str(tempchrdumpfile)
        os.system(awkcmd)

        num_Int = sum(1 for line in open(tempchrdumpfile))
        if num_Int == 0:
            continue

        G = nx.Graph()
        CurrChrDict = dict()

        with open(tempchrdumpfile, 'r') as fp:
            for line in fp:
                linecontents = (line.rstrip()).split()
                bin1 = int(int(linecontents[2]) / bin_size)
                bin2 = int(int(linecontents[5]) / bin_size)
                if bin1 < bin2:
                    curr_key = (bin1, bin2)
                else:
                    curr_key = (bin2, bin1)
                CurrChrDict.setdefault(curr_key, Interaction(int(linecontents[CCCol-1]), float(linecontents[PValCol - 1]), float(linecontents[QValCol - 1])))
                G.add_node(curr_key)

        nodelist = list(G.nodes())
        for i in range(len(nodelist) - 1):
            node1 = nodelist[i]
            for j in range(i+1, len(nodelist)):
                node2 = nodelist[j]
                if connectivity_rule == 8:
                    if (abs(node1[0] - node2[0]) <= 1) and (abs(node1[1] - node2[1]) <= 1):
                        G.add_edge(node1, node2)
                if connectivity_rule == 4:
                    if ((abs(node1[0] - node2[0]) + abs(node1[1] - node2[1])) <= 1):
                        G.add_edge(node1, node2)

        print('No of nodes of G: ', G.number_of_nodes())
        print('No of edges of G: ', G.number_of_edges())
        print('Number of connected components of G: ', nx.number_connected_components(G))

        list_conn_comp = sorted(nx.connected_components(G), key=len, reverse=True)

        for i in range(len(list_conn_comp)):
            curr_comp_list = list(list_conn_comp[i])
            min_idx_bin1 = min([x[0] for x in curr_comp_list])
            max_idx_bin1 = max([x[0] for x in curr_comp_list])
            span_low_bin1 = (min_idx_bin1 - 1) * bin_size
            span_high_bin1 = max_idx_bin1 * bin_size
            min_idx_bin2 = min([x[1] for x in curr_comp_list])
            max_idx_bin2 = max([x[1] for x in curr_comp_list])
            span_low_bin2 = (min_idx_bin2 - 1) * bin_size
            span_high_bin2 = max_idx_bin2 * bin_size
            sum_cc = sum([CurrChrDict[x]._GetCC() for x in curr_comp_list])

            total_possible_bin_pairs = (max_idx_bin1 - min_idx_bin1 + 1) * (max_idx_bin2 - min_idx_bin2 + 1)
            possible_bin_pairs = 0
            for b1 in range(min_idx_bin1, (max_idx_bin1 + 1)):
                for b2 in range(min_idx_bin2, (max_idx_bin2 + 1)):
                    bin_pair_key = (b1, b2)
                    if bin_pair_key in CurrChrDict:
                        possible_bin_pairs += 1
            Percent_Significant_BinPair = (possible_bin_pairs * 1.0) / total_possible_bin_pairs

            if TopPctElem == 0:
                for j in range(len(curr_comp_list)):
                    curr_key = curr_comp_list[j]
                    curr_cc = CurrChrDict[curr_key]._GetCC()
                    curr_pval = CurrChrDict[curr_key]._GetPVal()
                    curr_qval = CurrChrDict[curr_key]._GetQVal()
                    if j == 0:
                        rep_bin_key = curr_key
                    elif (SortOrder == 0) and (curr_pval < CurrChrDict[rep_bin_key]._GetPVal()) and (curr_qval < CurrChrDict[rep_bin_key]._GetQVal()):
                        rep_bin_key = curr_key
                    elif (SortOrder == 1) and (curr_pval > CurrChrDict[rep_bin_key]._GetPVal()) and (curr_qval > CurrChrDict[rep_bin_key]._GetQVal()):
                        rep_bin_key = curr_key
                    elif (curr_pval == CurrChrDict[rep_bin_key]._GetPVal()) and (curr_qval == CurrChrDict[rep_bin_key]._GetQVal()) and (curr_cc > CurrChrDict[rep_bin_key]._GetCC()):
                        rep_bin_key = curr_key
                rep_bin1_low = (rep_bin_key[0] - 1) * bin_size
                rep_bin1_high = rep_bin_key[0] * bin_size
                rep_bin2_low = (rep_bin_key[1] - 1) * bin_size
                rep_bin2_high = rep_bin_key[1] * bin_size
                cc = CurrChrDict[rep_bin_key]._GetCC()
                pval = CurrChrDict[rep_bin_key]._GetPVal()
                qval = CurrChrDict[rep_bin_key]._GetQVal()
                fp_outInt.write('\n' + str(curr_chr) + '\t' + str(rep_bin1_low) + '\t' + str(rep_bin1_high) + '\t' + str(curr_chr) + '\t' + str(rep_bin2_low) + '\t' + str(rep_bin2_high) + '\t' + str(cc) + '\t' + str(pval) + '\t' + str(qval) + '\t' + str(span_low_bin1) + '\t' + str(span_high_bin1) + '\t' + str(span_low_bin2) + '\t' + str(span_high_bin2) + '\t' + str(sum_cc) + '\t' + str(Percent_Significant_BinPair))

            elif TopPctElem < 100:
                Curr_Comp_Tuple_List = []
                curr_conn_comp_CCList = []
                curr_conn_comp_QValList = []
                for j in range(len(curr_comp_list)):
                    curr_key = curr_comp_list[j]
                    curr_cc = CurrChrDict[curr_key]._GetCC()
                    curr_pval = CurrChrDict[curr_key]._GetPVal()
                    curr_qval = CurrChrDict[curr_key]._GetQVal()
                    curr_conn_comp_CCList.append(curr_cc)
                    curr_conn_comp_QValList.append(curr_qval)
                    if SortOrder == 0:
                        subl = [curr_qval, ((-1) * curr_cc), curr_key[0], curr_key[1]]
                    else:
                        subl = [((-1) * curr_qval), ((-1) * curr_cc), curr_key[0], curr_key[1]]
                    heapq.heappush(Curr_Comp_Tuple_List, subl)
                max_cc = max(curr_conn_comp_CCList)
                min_qval = min(curr_conn_comp_QValList)
                custom_cc = custom_percent(curr_conn_comp_CCList, TopPctElem, 2)
                custom_qval = custom_percent(curr_conn_comp_QValList, TopPctElem, (SortOrder+1))
                Final_Rep_Key_List = []
                while len(Curr_Comp_Tuple_List) > 0:
                    curr_elem = heapq.heappop(Curr_Comp_Tuple_List)
                    if ((SortOrder == 0) and (curr_elem[0] > custom_qval)) or ((SortOrder == 1) and (curr_elem[0] < custom_qval)):
                        break
                    if len(Final_Rep_Key_List) == 0:
                        subl = [curr_elem[2], curr_elem[3]]
                        Final_Rep_Key_List.append(subl)
                        continue
                    flag = False
                    for i in range(len(Final_Rep_Key_List)):
                        if (((abs(Final_Rep_Key_List[i][0] - curr_elem[2])) * bin_size) <= NeighborHoodBinThr) and (((abs(Final_Rep_Key_List[i][1] - curr_elem[3])) * bin_size) <= NeighborHoodBinThr):
                            flag = True
                            break
                    if flag == False:
                        subl = [curr_elem[2], curr_elem[3]]
                        Final_Rep_Key_List.append(subl)
                for i in range(len(Final_Rep_Key_List)):
                    rep_bin_key = (Final_Rep_Key_List[i][0], Final_Rep_Key_List[i][1])
                    rep_bin1_low = (rep_bin_key[0] - 1) * bin_size
                    rep_bin1_high = rep_bin_key[0] * bin_size
                    rep_bin2_low = (rep_bin_key[1] - 1) * bin_size
                    rep_bin2_high = rep_bin_key[1] * bin_size
                    cc = CurrChrDict[rep_bin_key]._GetCC()
                    pval = CurrChrDict[rep_bin_key]._GetPVal()
                    qval = CurrChrDict[rep_bin_key]._GetQVal()
                    fp_outInt.write('\n' + str(curr_chr) + '\t' + str(rep_bin1_low) + '\t' + str(rep_bin1_high) + '\t' + str(curr_chr) + '\t' + str(rep_bin2_low) + '\t' + str(rep_bin2_high) + '\t' + str(cc) + '\t' + str(pval) + '\t' + str(qval) + '\t' + str(span_low_bin1) + '\t' + str(span_high_bin1) + '\t' + str(span_low_bin2) + '\t' + str(span_high_bin2) + '\t' + str(sum_cc) + '\t' + str(Percent_Significant_BinPair))

            else:  # TopPctElem == 100
                Curr_Comp_Tuple_List = []
                curr_conn_comp_CCList = []
                curr_conn_comp_QValList = []
                for j in range(len(curr_comp_list)):
                    curr_key = curr_comp_list[j]
                    curr_cc = CurrChrDict[curr_key]._GetCC()
                    curr_qval = CurrChrDict[curr_key]._GetQVal()
                    curr_conn_comp_CCList.append(curr_cc)
                    curr_conn_comp_QValList.append(curr_qval)
                    if SortOrder == 0:
                        subl = [curr_qval, ((-1) * curr_cc), curr_key[0], curr_key[1]]
                    else:
                        subl = [((-1) * curr_qval), ((-1) * curr_cc), curr_key[0], curr_key[1]]
                    heapq.heappush(Curr_Comp_Tuple_List, subl)
                Final_Rep_Key_List = []
                while len(Curr_Comp_Tuple_List) > 0:
                    curr_elem = heapq.heappop(Curr_Comp_Tuple_List)
                    if len(Final_Rep_Key_List) == 0:
                        subl = [curr_elem[2], curr_elem[3]]
                        Final_Rep_Key_List.append(subl)
                        continue
                    flag = False
                    for i in range(len(Final_Rep_Key_List)):
                        if (((abs(Final_Rep_Key_List[i][0] - curr_elem[2])) * bin_size) <= NeighborHoodBinThr) and (((abs(Final_Rep_Key_List[i][1] - curr_elem[3])) * bin_size) <= NeighborHoodBinThr):
                            flag = True
                            break
                    if flag == False:
                        subl = [curr_elem[2], curr_elem[3]]
                        Final_Rep_Key_List.append(subl)
                for i in range(len(Final_Rep_Key_List)):
                    rep_bin_key = (Final_Rep_Key_List[i][0], Final_Rep_Key_List[i][1])
                    rep_bin1_low = (rep_bin_key[0] - 1) * bin_size
                    rep_bin1_high = rep_bin_key[0] * bin_size
                    rep_bin2_low = (rep_bin_key[1] - 1) * bin_size
                    rep_bin2_high = rep_bin_key[1] * bin_size
                    cc = CurrChrDict[rep_bin_key]._GetCC()
                    pval = CurrChrDict[rep_bin_key]._GetPVal()
                    qval = CurrChrDict[rep_bin_key]._GetQVal()
                    fp_outInt.write('\n' + str(curr_chr) + '\t' + str(rep_bin1_low) + '\t' + str(rep_bin1_high) + '\t' + str(curr_chr) + '\t' + str(rep_bin2_low) + '\t' + str(rep_bin2_high) + '\t' + str(cc) + '\t' + str(pval) + '\t' + str(qval) + '\t' + str(span_low_bin1) + '\t' + str(span_high_bin1) + '\t' + str(span_low_bin2) + '\t' + str(span_high_bin2) + '\t' + str(sum_cc) + '\t' + str(Percent_Significant_BinPair))

    fp_outInt.close()

    # remove temporary file only if it exists
    if os.path.exists(tempchrdumpfile):
        os.system("rm " + str(tempchrdumpfile))

    print('==================== End of merge filtering adjacent interactions !!! ======================')

if __name__ == "__main__":
    main()