#!/usr/bin/env python3
import os
import argparse
import subprocess
import json
import re
import glob
import sys

def main():
    # Argument parser setup
    parser = argparse.ArgumentParser(description="Run the TOBIAS for ATAC-seq footprinting analysis on enhancer regions.")
    parser.add_argument("-o", "--output_dir", required=True, help="Path to the output directory where results will be saved, same as the Hichipsnake step (e.g., /path/to/output/).")
    parser.add_argument("--organism", required=True, help="Reference genome assembly to use, created by the Genomesetup step (e.g., 'hg38' or 'mm10').")
    parser.add_argument("--genome_dir", required=True, help="Absolute path to the directory containing pre-generated genome files, created by the Genomesetup step (e.g., /absolute/path/to/genomes/).")
    parser.add_argument("--enhancer_bedpe", required=True, help="Space-separated list of enhancer BEDPE files, generated by the Hichipsnake step (e.g., 'sample1.bedpe sample2.bedpe' or 'sample1.bedpe').")
    parser.add_argument("--atacseq_bam", required=True, help="Space-separated list of ATAC-seq BAM files (e.g., 'sample1.bam sample2.bam' or 'sample1.bam').")
    parser.add_argument("--samples", required=True, help="Space-separated list of sample names corresponding to BAM files (e.g., 'sample1 sample2' or 'sample1').")
    parser.add_argument("--threads", type=int, default=30, help="Number of CPU threads to use for parallel processing (default: 30).")
    parser.add_argument("--motifs", nargs="+", default="NA", help="Absolute path to a directory or space-separated list of motif files in PFM/MEME/JASPAR format (e.g., 'motif1.pfm motif2.pfm'). Default: none.")
    parser.add_argument("--atacorrect", default="NA", help="Optional space-separated parameters to pass to ATACorrect (e.g., '--read_shift 5'). Default: none.")
    parser.add_argument("--footprinting", default="NA", help="Optional space-separated parameters to pass to ScoreBigwig (e.g., '--signal_smoothing 10'). Default: none.")
    parser.add_argument("--bindetect", default="NA", help="Optional space-separated parameters to pass to BINDetect (e.g., '--threshold 0.05'). Default: none.")
    parser.add_argument("--plot_aggregate", default="NA", help="Optional space-separated parameters to pass to PlotAggregate (e.g., '--plot_type line'). Default: none.")
    parser.add_argument("--plot_changes", default="NA", help="Optional space-separated parameters to pass to PlotChanges (e.g., '--color red'). Default: none.")

    # Parse known arguments, capturing extra Snakemake args
    args, extra_args = parser.parse_known_args()

    # Assign variables from parsed arguments
    output_dir = os.path.abspath(args.output_dir)
    organism = args.organism
    genome_dir = args.genome_dir
    atacseq_bam = args.atacseq_bam.split()  # Split into list
    enhancer_bedpe = args.enhancer_bedpe.split()  # Split into list
    samples = args.samples.split()  # Split into list
    motifs = args.motifs  # Ensure absolute paths
    atacorrect = args.atacorrect
    footprinting = args.footprinting
    plot_aggregate = args.plot_aggregate
    plot_changes = args.plot_changes
    bindetect = args.bindetect
    threads = args.threads

    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)

    # Determine script directory
    script_dir = os.path.dirname(os.path.abspath(__file__))

    # Validate inputs
    if len(atacseq_bam) != len(samples):
        sys.stderr.write(
            f"Error: Number of BAM files ({len(atacseq_bam)}) does not match number of samples ({len(samples)}).\n"
            "Please ensure --atacseq_bam and --samples have the same number of elements.\n"
        )
        sys.exit(1)

    # Check if input files exist
    for bam in atacseq_bam:
        if not os.path.exists(bam):
            sys.stderr.write(f"Error: BAM file '{bam}' does not exist.\n")
            sys.exit(1)

    for bedpe in enhancer_bedpe:
        if not os.path.exists(bedpe):
            sys.stderr.write(f"Error: BEDPE file '{bedpe}' does not exist.\n")
            sys.exit(1)

    if motifs != "NA":
        for motif in motifs:
            if not os.path.exists(motif):
                sys.stderr.write(f"Error: Motif file '{motif}' does not exist.\n")
                sys.exit(1)

    # Build Snakemake command
    snakemake_cmd = [
        "snakemake",
        "--snakefile", os.path.join(script_dir, "../rules/TFtobias.Snakefile"),  # Adjust Snakefile name as needed
        "--printshellcmds",
        "--directory", output_dir,
        "--use-conda",
        "--conda-prefix", os.path.join(genome_dir, ".snakemake_conda"),
        "--config",
        f"organism={organism}",
        f"genome_dir={genome_dir}",
        f"atacseq_bam={' '.join(atacseq_bam)}",  # Join back as space-separated string
        f"enhancer_bedpe={' '.join(enhancer_bedpe)}",  # Join back as space-separated string
        f"samples={json.dumps(samples)}",
        f"motifs={json.dumps(motifs)}",
        f"atacorrect={atacorrect}",
        f"footprinting={footprinting}",
        f"plot_aggregate={plot_aggregate}",
        f"plot_changes={plot_changes}",
        f"bindetect={bindetect}",
        f"threads={threads}",
        "--cores", str(threads),
    ]

    # Append any extra Snakemake arguments
    if extra_args:
        snakemake_cmd.extend(extra_args)

    # Generate unique log file name
    log_pattern = os.path.join(output_dir, "tftobias_run_*.log")
    log_number = max([int(re.search(r"tftobias_run_(\d+)\.log", f).group(1)) 
                    for f in glob.glob(log_pattern)], default=0) + 1
    log_file_path = os.path.join(output_dir, f"tftobias_run_{log_number}.log")

    # Log the command line
    command_line = " ".join(sys.argv)

    # Execute Snakemake with logging
    with open(log_file_path, "w") as log_file:
        # Write the command line to the log file
        log_file.write(f"Command line: {command_line}\n")
        log_file.write("-" * 80 + "\n")  # Separator for clarity
        process = subprocess.Popen(
            snakemake_cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            universal_newlines=True
        )
        for line in process.stdout:
            print(line, end="")
            log_file.write(line)
        process.wait()
        if process.returncode != 0:
            raise subprocess.CalledProcessError(process.returncode, snakemake_cmd)


if __name__ == "__main__":
    main()